title: Justin Drew # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pronouns: They/Them/Their
  Student at UMBC pursuing Computer Science B.S. on the Data Science Track and the GIS Certificate. Class of 2020.
  <br><br>
  Strong background in machine learning and geospatial data analysis. Experienced with GIS Applications, SQL databases, and prediction modeling.
  <br><br>
  <a href="https://www.linkedin.com/in/justin-drew-6b1917140/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
