title: Justin Drew # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pronouns: They/Them/Their
  <br><br>   
  <a href="https://www.linkedin.com/in/justin-drew-6b1917140/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
